"""
Weave API routes — CGR3 reasoning and relation-context inspection.

Provides endpoints that are exclusive to WeaveGraph mode:

  POST /cgr3/query               — Iterative Retrieve→Rank→Reason query
  GET  /graph/edge/context       — Relation context for a specific edge
  GET  /graph/entity/edges-with-context — All context-enriched edges for an entity

All endpoints return HTTP 503 when the server is running plain WeaveEngine (i.e.
WEAVE_ENABLE_QUADRUPLE is not enabled), so clients can detect capability at runtime.
"""

from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional

from fastapi import APIRouter, Depends, HTTPException, Query
from pydantic import BaseModel, Field, field_validator

from weave.server.utils import get_combined_auth_dependency
from weave.server.routers.query import ReferenceItem
from weave_core.utils import logger

# ─────────────────────────────────────────────────────────────────────────────
# Pydantic models
# ─────────────────────────────────────────────────────────────────────────────


class CGR3QueryRequest(BaseModel):
    """Request body for the CGR3 iterative reasoning query."""

    query: str = Field(
        min_length=3,
        description="Natural language question to answer via iterative reasoning.",
    )
    mode: Literal["local", "global", "hybrid", "naive", "mix"] = Field(
        default="hybrid",
        description=(
            "Retrieval mode used in each CGR3 iteration. "
            "'hybrid' is recommended for multi-hop questions."
        ),
    )
    max_iterations: int = Field(
        default=3,
        ge=1,
        le=10,
        description=(
            "Maximum Retrieve→Rank→Reason iterations. "
            "The loop stops early when the LLM judges context sufficient."
        ),
    )
    top_k: Optional[int] = Field(
        default=None,
        ge=1,
        description="Number of entities/relations to retrieve per iteration.",
    )
    include_references: bool = Field(
        default=True,
        description="If True, include source citations in the response.",
    )

    @field_validator("query", mode="after")
    @classmethod
    def strip_query(cls, v: str) -> str:
        return v.strip()


class CGR3QueryResponse(BaseModel):
    """Response from a CGR3 iterative reasoning query."""

    response: str = Field(description="The final answer generated by CGR3.")
    references: Optional[List[ReferenceItem]] = Field(
        default=None,
        description="Source citations (present when include_references=True).",
    )


class RelationContextData(BaseModel):
    """Parsed relation context (rc) for a single edge."""

    supporting_sentences: List[str] = Field(
        default_factory=list,
        description="Direct verbatim quotes from source documents supporting this relationship.",
    )
    temporal_info: Optional[str] = Field(
        default=None,
        description="Validity period or timestamp (e.g., 'Q4 2026', 'since 2020').",
    )
    quantitative_data: Optional[str] = Field(
        default=None,
        description="Numerical data: amounts, percentages, counts.",
    )

    @field_validator("quantitative_data", "decision_trace", "provenance", "temporal_info", mode="before")
    @classmethod
    def coerce_to_str(cls, v):
        if isinstance(v, list):
            return ", ".join(str(item) for item in v)
        return v

    @field_validator("supporting_sentences", mode="before")
    @classmethod
    def coerce_to_list(cls, v):
        if isinstance(v, str):
            return [v]
        return v
    decision_trace: Optional[str] = Field(
        default=None,
        description="Rationale, exception, or approval behind this relationship.",
    )
    provenance: Optional[str] = Field(
        default=None,
        description="Source reference: Slack thread, transcript timestamp, document section.",
    )
    approved_by: Optional[str] = Field(
        default=None,
        description="Entity name of the approver (e.g., 'VP_Smith', 'Finance_Team').",
    )
    approved_via: Optional[str] = Field(
        default=None,
        description="Channel: 'slack', 'zoom', 'email', 'in_person', 'jira', 'system'.",
    )
    valid_from: Optional[str] = Field(
        default=None,
        description="ISO-8601 date when this decision became effective (e.g., '2024-08-14').",
    )
    valid_until: Optional[str] = Field(
        default=None,
        description="ISO-8601 date when this decision expires (e.g., '2024-12-31').",
    )
    policy_ref: Optional[str] = Field(
        default=None,
        description="Policy this decision follows or overrides (e.g., 'DiscountPolicy_Standard').",
    )
    confidence_score: float = Field(
        default=1.0,
        ge=0.0,
        le=1.0,
        description="Extraction reliability (0.0–1.0).",
    )


class EdgeContextResponse(BaseModel):
    """Relation context for a specific graph edge."""

    src_id: str = Field(description="Source entity (head).")
    tgt_id: str = Field(description="Target entity (tail).")
    has_context: bool = Field(
        description="True if a RelationContext was stored for this edge."
    )
    relation_context: Optional[RelationContextData] = Field(
        default=None,
        description="Parsed relation context (null if none was extracted).",
    )


class EdgeWithContext(BaseModel):
    """A single graph edge that carries a RelationContext."""

    src_id: str = Field(description="Source entity (head).")
    tgt_id: str = Field(description="Target entity (tail).")
    keywords: Optional[str] = Field(
        default=None, description="Relationship keywords."
    )
    description: Optional[str] = Field(
        default=None, description="Relationship description."
    )
    weight: float = Field(default=1.0, description="Relationship weight/frequency.")
    relation_context: RelationContextData = Field(
        description="Parsed relation context for this edge."
    )


class EdgesWithContextResponse(BaseModel):
    """All context-enriched edges connected to a given entity."""

    entity_name: str = Field(description="The queried entity.")
    total_count: int = Field(
        description="Number of edges with relation context found."
    )
    edges: List[EdgeWithContext] = Field(
        description="List of edges that carry a RelationContext."
    )


class EmitDecisionRequest(BaseModel):
    """Request body for recording a decision trace directly into the graph."""

    src: str = Field(min_length=1, description="Head entity name.")
    tgt: str = Field(min_length=1, description="Tail entity name.")
    relation_type: str = Field(
        min_length=1, description="Relationship keyword stored as edge keywords."
    )
    relation_context: RelationContextData = Field(
        description="The RelationContext capturing this decision."
    )

    @field_validator("src", "tgt", "relation_type", mode="before")
    @classmethod
    def _strip(cls, v):
        # Strip BEFORE validation so a whitespace-only id fails the min_length=1
        # check (a clean Pydantic 422) rather than writing an empty-id graph node
        # or 500-ing in storage. Done in 'before' mode so we don't raise a bare
        # ValueError (which this app's error handler can't JSON-serialize).
        return v.strip() if isinstance(v, str) else v


class EmitDecisionResponse(BaseModel):
    """Response after recording a decision trace."""

    status: str = Field(description="'ok' on success.")
    edge: str = Field(description="Edge identifier in 'src -> tgt' form.")
    outcome: Optional[str] = Field(
        default=None,
        description="Rules-gate outcome ('PASS'/'FLAG') when a gate is active; null otherwise.",
    )
    audit: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Rules-gate audit record (matched concept, score, threshold) when a gate is active.",
    )


class DecisionResult(BaseModel):
    """A single decision-bearing edge."""

    src_id: str = Field(description="Head entity.")
    tgt_id: str = Field(description="Tail entity.")
    relation_context: RelationContextData = Field(
        description="Parsed relation context for this decision."
    )


class DecisionsListResponse(BaseModel):
    """All decision-bearing edges, optionally filtered."""

    total_count: int = Field(description="Number of decisions returned.")
    decisions: List[DecisionResult] = Field(
        description="List of decision-bearing edges."
    )


class CommunityQueryRequest(BaseModel):
    """Request body for a thematic 'global' query over community summaries."""

    query: str = Field(min_length=1, description="The thematic question.")
    top_k: int = Field(default=5, ge=1, le=20)


class IngestDecisionSummaryRequest(BaseModel):
    """Request body for ingesting an aggregated decision summary as a document."""

    text: str = Field(
        description="Natural-language summary of a group of related decisions."
    )
    category: str = Field(
        default="general",
        description="Grouping label (e.g. 'by_vehicle', 'by_outcome'). Used in file_path for identification.",
    )
    summary_id: Optional[str] = Field(
        default=None,
        description="Stable document ID for upsert semantics. If omitted, derived from text hash.",
    )


class IngestDecisionSummaryResponse(BaseModel):
    """Response after ingesting a decision summary."""

    status: str = Field(description="'ok' on success.")
    track_id: str = Field(description="Tracking ID for processing status.")
    summary_id: str = Field(description="Document ID assigned to the summary.")


class PrecedentResult(BaseModel):
    """A single precedent result from semantic search."""

    src_id: str = Field(description="Head entity.")
    tgt_id: str = Field(description="Tail entity.")
    relation_context: RelationContextData = Field(
        description="Parsed relation context for this precedent."
    )


class PrecedentsSearchResponse(BaseModel):
    """Results of a precedent search."""

    query: str = Field(description="The search query text.")
    total_count: int = Field(description="Number of precedents found.")
    results: List[PrecedentResult] = Field(
        description="Ranked list of semantically similar past decisions."
    )


# ─────────────────────────────────────────────────────────────────────────────
# Helper
# ─────────────────────────────────────────────────────────────────────────────


def _rc_to_pydantic(rc) -> RelationContextData:
    """Convert a RelationContext dataclass instance to a Pydantic model."""
    return RelationContextData(
        supporting_sentences=rc.supporting_sentences or [],
        temporal_info=rc.temporal_info,
        quantitative_data=rc.quantitative_data,
        decision_trace=rc.decision_trace,
        provenance=rc.provenance,
        approved_by=rc.approved_by,
        approved_via=rc.approved_via,
        valid_from=rc.valid_from,
        valid_until=rc.valid_until,
        policy_ref=rc.policy_ref,
        confidence_score=rc.confidence_score,
    )


def _pydantic_to_rc(data: RelationContextData):
    """Convert a RelationContextData Pydantic model to a RelationContext dataclass."""
    from weave_core.graph.types import RelationContext

    return RelationContext(
        supporting_sentences=data.supporting_sentences or [],
        temporal_info=data.temporal_info,
        quantitative_data=data.quantitative_data,
        decision_trace=data.decision_trace,
        provenance=data.provenance,
        approved_by=data.approved_by,
        approved_via=data.approved_via,
        valid_from=data.valid_from,
        valid_until=data.valid_until,
        policy_ref=data.policy_ref,
        confidence_score=data.confidence_score,
    )


def _require_quadruple(rag):
    """Raise HTTP 503 if rag is not a WeaveGraph instance."""
    from weave_core.graph.quadruple import WeaveGraph

    if not isinstance(rag, WeaveGraph):
        raise HTTPException(
            status_code=503,
            detail=(
                "This endpoint requires the governance engine. "
                "Set WEAVE_ENABLE_QUADRUPLE=true in your .env or configuration."
            ),
        )


# ─────────────────────────────────────────────────────────────────────────────
# Route factory
# ─────────────────────────────────────────────────────────────────────────────


def create_reasoning_routes(
    rag,
    api_key: Optional[str] = None,
    cgr3_max_iterations: int = 3,
    top_k: int = 60,
):
    """Create and return the Weave router, bound to the given *rag* instance."""

    # Create a fresh router per factory call so that each invocation gets its
    # own closure over `rag` (important for tests and multi-instance setups).
    router = APIRouter(tags=["weave"])

    combined_auth = get_combined_auth_dependency(api_key)

    # Background reindex bookkeeping (per app instance):
    #  - _reindex_tasks holds strong refs so a fire-and-forget task is not
    #    garbage-collected mid-run (documented asyncio pitfall);
    #  - _reindex_running guards against overlapping rebuilds on the same workspace.
    _reindex_tasks: set = set()
    _reindex_running: set = set()

    # ── CGR3 Query ────────────────────────────────────────────────────────────

    @router.post(
        "/cgr3/query",
        response_model=CGR3QueryResponse,
        dependencies=[Depends(combined_auth)],
        summary="CGR3 iterative reasoning query",
        responses={
            200: {
                "description": "Answer produced by the CGR3 Retrieve→Rank→Reason loop.",
                "content": {
                    "application/json": {
                        "example": {
                            "response": "The 20% discount was approved by the VP of Sales citing a five-year relationship and competitive pressure from Salesforce (valid until Q4 2024).",
                            "references": [
                                {
                                    "reference_id": "1",
                                    "file_path": "/documents/q3_review.txt",
                                }
                            ],
                        }
                    }
                },
            },
            503: {
                "description": "Weave mode is not enabled on this server.",
                "content": {
                    "application/json": {
                        "example": {
                            "detail": "This endpoint requires the governance engine. Set WEAVE_ENABLE_QUADRUPLE=true (separate from WEAVE_ENABLE_TEAM)."
                        }
                    }
                },
            },
        },
    )
    async def cgr3_query(request: CGR3QueryRequest):
        """
        Answer a question using the **CGR3** paradigm (Retrieve → Rank → Reason).

        Unlike a standard query that calls the LLM once, CGR3 iterates:

        1. **Retrieve** — gather candidate entities and relationships with their
           RelationContext (temporal validity, decision traces, provenance).
        2. **Rank** — ask the LLM to order candidates by contextual relevance.
        3. **Reason** — check whether the context is sufficient to answer.
           If not, use the top-ranked entities as seeds for the next iteration.

        The loop repeats up to `max_iterations` times, accumulating richer context
        with each pass — ideal for multi-hop and decision-trace queries.

        **Example request:**
        ```json
        {
            "query": "Why did we discount the MegaCorp deal in Q3?",
            "mode": "hybrid",
            "max_iterations": 3,
            "top_k": 60
        }
        ```

        **Requires:** `WEAVE_ENABLE_QUADRUPLE=true` in server configuration.
        """
        _require_quadruple(rag)
        try:
            resolved_top_k = request.top_k or top_k
            resolved_iterations = request.max_iterations or cgr3_max_iterations

            answer = await rag.cgr3_query(
                query=request.query,
                mode=request.mode,
                max_iterations=resolved_iterations,
                top_k=resolved_top_k,
            )

            return CGR3QueryResponse(
                response=answer,
                references=None,  # CGR3 collects context internally; no per-chunk refs
            )
        except HTTPException:
            raise
        except Exception as e:
            logger.error(f"CGR3 query error: {e}", exc_info=True)
            raise HTTPException(status_code=500, detail=str(e))

    # ── Edge context ──────────────────────────────────────────────────────────

    @router.get(
        "/graph/edge/context",
        response_model=EdgeContextResponse,
        # Pinned, not derived. FastAPI builds an operationId from the handler
        # name and the path, and for this route that join lands on the source
        # product's name by pure accident — a banned token (A3) in the public
        # OpenAPI contract, which the name-guard cannot see because it is
        # generated at runtime rather than written down.
        operation_id="get_edge_relation_context",
        dependencies=[Depends(combined_auth)],
        summary="Get relation context for a graph edge",
        responses={
            200: {
                "description": "Relation context for the requested edge.",
                "content": {
                    "application/json": {
                        "examples": {
                            "with_context": {
                                "summary": "Edge with extracted relation context",
                                "value": {
                                    "src_id": "Sarah Chen",
                                    "tgt_id": "MegaCorp",
                                    "has_context": True,
                                    "relation_context": {
                                        "supporting_sentences": [
                                            "Sarah Chen approved a 20% discount for MegaCorp"
                                        ],
                                        "temporal_info": "Valid until December 31, 2024",
                                        "quantitative_data": "20% discount",
                                        "decision_trace": "VP approved citing five-year relationship and Salesforce competition",
                                        "provenance": "Slack #deals-review, August 14 2024",
                                        "confidence_score": 0.97,
                                    },
                                },
                            },
                            "no_context": {
                                "summary": "Edge without relation context",
                                "value": {
                                    "src_id": "Alice",
                                    "tgt_id": "Bob",
                                    "has_context": False,
                                    "relation_context": None,
                                },
                            },
                        }
                    }
                },
            },
            404: {
                "description": "Edge not found in the knowledge graph.",
                "content": {
                    "application/json": {
                        "example": {
                            "detail": "No edge found between 'Alice' and 'Bob'."
                        }
                    }
                },
            },
            503: {
                "description": "Weave mode is not enabled.",
            },
        },
    )
    async def get_edge_context(
        src: str = Query(
            ...,
            description="Source entity name (head of the relationship).",
            example="Sarah Chen",
        ),
        tgt: str = Query(
            ...,
            description="Target entity name (tail of the relationship).",
            example="MegaCorp",
        ),
    ):
        """
        Retrieve the **RelationContext** (`rc`) stored for a specific knowledge graph edge.

        The RelationContext is the 4th component of the contextual quadruple `(h, r, t, rc)`
        and captures:
        - **supporting_sentences**: Direct verbatim quotes from source documents
        - **temporal_info**: Validity period (e.g., "Q4 2026")
        - **quantitative_data**: Numerical data (discounts, amounts)
        - **decision_trace**: The "why" — exceptions, approvals, rationale
        - **provenance**: Source reference (Slack thread, call transcript, document)
        - **confidence_score**: Extraction reliability

        **Requires:** `WEAVE_ENABLE_QUADRUPLE=true` in server configuration.
        """
        _require_quadruple(rag)
        try:
            # Check edge exists (try both directions — undirected graph)
            graph = rag.chunk_entity_relation_graph
            has_edge = await graph.has_edge(src, tgt) or await graph.has_edge(tgt, src)
            if not has_edge:
                raise HTTPException(
                    status_code=404,
                    detail=f"No edge found between '{src}' and '{tgt}'.",
                )

            rc = await rag.get_edge_context(src, tgt)
            if rc is None:
                # Try reverse direction
                rc = await rag.get_edge_context(tgt, src)

            return EdgeContextResponse(
                src_id=src,
                tgt_id=tgt,
                has_context=rc is not None and not rc.is_empty(),
                relation_context=_rc_to_pydantic(rc) if rc and not rc.is_empty() else None,
            )
        except HTTPException:
            raise
        except Exception as e:
            logger.error(f"get_edge_context error: {e}", exc_info=True)
            raise HTTPException(status_code=500, detail=str(e))

    # ── Entity edges with context ─────────────────────────────────────────────

    @router.get(
        "/graph/entity/edges-with-context",
        response_model=EdgesWithContextResponse,
        operation_id="list_entity_edges_with_relation_context",   # pinned, see above
        dependencies=[Depends(combined_auth)],
        summary="List context-enriched edges for an entity",
        responses={
            200: {
                "description": "All edges connected to the entity that carry a RelationContext.",
                "content": {
                    "application/json": {
                        "example": {
                            "entity_name": "Sarah Chen",
                            "total_count": 2,
                            "edges": [
                                {
                                    "src_id": "Sarah Chen",
                                    "tgt_id": "MegaCorp",
                                    "keywords": "discount approval, deal negotiation",
                                    "description": "Sarah Chen approved a 20% discount for MegaCorp.",
                                    "weight": 1.5,
                                    "relation_context": {
                                        "supporting_sentences": [
                                            "Sarah Chen approved a 20% discount"
                                        ],
                                        "temporal_info": "Valid until December 31, 2024",
                                        "quantitative_data": "20% discount",
                                        "decision_trace": "VP approved due to competitive pressure",
                                        "provenance": "Slack #deals-review",
                                        "confidence_score": 0.97,
                                    },
                                }
                            ],
                        }
                    }
                },
            },
            404: {
                "description": "Entity not found in the knowledge graph.",
                "content": {
                    "application/json": {
                        "example": {
                            "detail": "Entity 'Unknown Person' not found in the knowledge graph."
                        }
                    }
                },
            },
            503: {
                "description": "Weave mode is not enabled.",
            },
        },
    )
    async def get_entity_edges_with_context(
        entity_name: str = Query(
            ...,
            description="Entity name to look up connected edges for.",
            example="Sarah Chen",
        ),
    ):
        """
        Return all knowledge graph edges connected to *entity_name* that carry
        a **RelationContext** (`rc`).

        This is useful for exploring the decision traces, approvals, and evidence
        surrounding a specific entity (lead, opportunity, stakeholder, etc.).

        Only edges that were extracted with Weave mode (and therefore
        have a stored `rc` JSON blob) are returned; plain triple-based edges
        without context are omitted.

        **Requires:** `WEAVE_ENABLE_QUADRUPLE=true` in server configuration.
        """
        _require_quadruple(rag)
        try:
            graph = rag.chunk_entity_relation_graph
            if not await graph.has_node(entity_name):
                raise HTTPException(
                    status_code=404,
                    detail=f"Entity '{entity_name}' not found in the knowledge graph.",
                )

            raw_edges = await rag.get_edges_with_context(entity_name)

            edges_out: List[EdgeWithContext] = []
            for edge in raw_edges:
                rc = edge.get("relation_context")
                if rc is None:
                    continue
                # rc is already a RelationContext dataclass (from get_edges_with_context)
                from weave_core.graph.types import RelationContext

                if isinstance(rc, str):
                    rc = RelationContext.from_json(rc)

                edges_out.append(
                    EdgeWithContext(
                        src_id=edge.get("src_id", ""),
                        tgt_id=edge.get("tgt_id", ""),
                        keywords=edge.get("keywords"),
                        description=edge.get("description"),
                        weight=float(edge.get("weight", 1.0)),
                        relation_context=_rc_to_pydantic(rc),
                    )
                )

            return EdgesWithContextResponse(
                entity_name=entity_name,
                total_count=len(edges_out),
                edges=edges_out,
            )
        except HTTPException:
            raise
        except Exception as e:
            logger.error(f"get_entity_edges_with_context error: {e}", exc_info=True)
            raise HTTPException(status_code=500, detail=str(e))

    # ── Emit decision trace ────────────────────────────────────────────────────

    @router.post(
        "/graph/decision/emit",
        response_model=EmitDecisionResponse,
        dependencies=[Depends(combined_auth)],
        summary="Record a decision trace directly into the graph",
        responses={
            200: {
                "description": "Decision trace recorded successfully.",
                "content": {
                    "application/json": {
                        "example": {
                            "status": "ok",
                            "edge": "Sarah Chen -> MegaCorp",
                            "outcome": "FLAG",
                            "audit": {
                                "outcome": "FLAG",
                                "rule": "large discount needs finance review",
                                "matched_concept": "APPROVAL",
                                "score": 1.0,
                                "threshold": 0.4,
                            },
                        }
                    }
                },
            },
            422: {
                "description": "A business rule REJECTed the decision; nothing was persisted.",
                "content": {
                    "application/json": {
                        "example": {
                            "detail": {
                                "status": "rejected",
                                "outcome": "REJECT",
                                "audit": {"outcome": "REJECT", "rule": "discount cap"},
                            }
                        }
                    }
                },
            },
            503: {"description": "Weave mode is not enabled."},
        },
    )
    async def emit_decision(request: EmitDecisionRequest):
        """
        Record a **decision trace** directly into the knowledge graph at runtime.

        Unlike `ainsert()` which extracts context from prose after the fact,
        this endpoint writes a structured `RelationContext` to a graph edge
        immediately — ideal for agent orchestration code to call at the moment
        a decision is made.

        If the edge already exists, the new `RelationContext` is **merged** with
        the existing one (supporting_sentences are unioned; scalar fields use
        first-non-null; confidence is the maximum).

        The `decision_trace` text is also indexed in the decisions vector store,
        enabling future **precedent search** via `/graph/decisions/search`.

        **Requires:** `WEAVE_ENABLE_QUADRUPLE=true` in server configuration.
        """
        _require_quadruple(rag)
        from weave_core.governance.rules.gate import RuleViolation

        try:
            rc = _pydantic_to_rc(request.relation_context)
            decision = await rag.emit_decision_trace(
                src=request.src,
                tgt=request.tgt,
                relation_type=request.relation_type,
                rc=rc,
            )
            return EmitDecisionResponse(
                status="ok",
                edge=f"{request.src} -> {request.tgt}",
                outcome=decision.outcome if decision is not None else None,
                audit=decision.audit if decision is not None else None,
            )
        except RuleViolation as e:
            # A business rule REJECTed the decision — nothing was persisted.
            raise HTTPException(
                status_code=422,
                detail={"status": "rejected", "outcome": "REJECT", "audit": e.decision.audit},
            )
        except HTTPException:
            raise
        except Exception as e:
            logger.error(f"emit_decision error: {e}", exc_info=True)
            raise HTTPException(status_code=500, detail=str(e))

    # ── Decision summary ingestion ───────────────────────────────────────────

    @router.post(
        "/graph/decisions/ingest-summary",
        response_model=IngestDecisionSummaryResponse,
        dependencies=[Depends(combined_auth)],
        summary="Ingest an aggregated decision summary as a searchable document",
        responses={
            200: {
                "description": "Decision summary ingested and queued for processing.",
                "content": {
                    "application/json": {
                        "example": {
                            "status": "ok",
                            "track_id": "insert_1710000000000_abc",
                            "summary_id": "dsum-a1b2c3d4e5",
                        }
                    }
                },
            },
            503: {"description": "Weave mode is not enabled."},
        },
    )
    async def ingest_decision_summary(request: IngestDecisionSummaryRequest):
        """
        Ingest an **aggregated decision summary** as a standard document.

        Unlike `/graph/decision/emit` which writes individual edges to a
        separate decisions vector store, this endpoint pipes the summary text
        through the full ingestion pipeline — creating chunks, entity/relation
        embeddings, and graph nodes.  This makes the summary discoverable by
        standard `/query` and CGR3 queries.

        The **caller** is responsible for aggregating raw decisions into
        meaningful natural-language summaries.  This endpoint is domain-agnostic.

        **Example request:**
        ```json
        {
            "text": "Out of 47 discount requests for sedans, 38 were approved (81%)...",
            "category": "by_vehicle_type",
            "summary_id": "sedan-discount-patterns"
        }
        ```

        **Requires:** `WEAVE_ENABLE_QUADRUPLE=true` in server configuration.
        """
        _require_quadruple(rag)
        try:
            from weave_core.utils import compute_mdhash_id

            summary_id = request.summary_id or compute_mdhash_id(
                request.text, prefix="dsum-"
            )
            track_id = await rag.ingest_decision_summary(
                text=request.text,
                category=request.category,
                summary_id=summary_id,
            )
            return IngestDecisionSummaryResponse(
                status="ok",
                track_id=track_id,
                summary_id=summary_id,
            )
        except HTTPException:
            raise
        except Exception as e:
            logger.error(f"ingest_decision_summary error: {e}", exc_info=True)
            raise HTTPException(status_code=500, detail=str(e))

    # ── Precedent search ──────────────────────────────────────────────────────

    @router.get(
        "/graph/decisions/search",
        response_model=PrecedentsSearchResponse,
        dependencies=[Depends(combined_auth)],
        summary="Semantic search for past decisions similar to a query",
        responses={
            200: {
                "description": "Ranked list of semantically similar past decisions.",
            },
            503: {"description": "Weave mode is not enabled."},
        },
    )
    async def search_decisions(
        q: str = Query(
            ...,
            description="Natural language description of the decision scenario to search for.",
            example="20% discount approved for a long-term client under competitive pressure",
        ),
        top_k: int = Query(
            default=10,
            ge=1,
            le=100,
            description="Maximum number of precedents to return.",
        ),
        min_confidence: float = Query(
            default=0.0,
            ge=0.0,
            le=1.0,
            description="Minimum confidence score threshold.",
        ),
    ):
        """
        Find past decisions **semantically similar** to *q* using vector similarity
        over indexed `decision_trace` text.

        Enables queries like:
        - *"Find precedents where a discount was approved due to competitive pressure"*
        - *"Show me past exceptions to the standard pricing policy"*

        Only decisions recorded via `ainsert()` or `POST /graph/decision/emit`
        are indexed.

        **Requires:** `WEAVE_ENABLE_QUADRUPLE=true` in server configuration.
        """
        _require_quadruple(rag)
        try:
            raw = await rag.find_precedents(
                query_text=q,
                top_k=top_k,
                min_confidence=min_confidence,
            )
            results = [
                PrecedentResult(
                    src_id=item["src_id"],
                    tgt_id=item["tgt_id"],
                    relation_context=_rc_to_pydantic(item["relation_context"]),
                )
                for item in raw
            ]
            return PrecedentsSearchResponse(
                query=q,
                total_count=len(results),
                results=results,
            )
        except HTTPException:
            raise
        except Exception as e:
            logger.error(f"search_decisions error: {e}", exc_info=True)
            raise HTTPException(status_code=500, detail=str(e))

    # ── List / filter decisions ───────────────────────────────────────────────

    @router.get(
        "/graph/decisions",
        response_model=DecisionsListResponse,
        dependencies=[Depends(combined_auth)],
        summary="List all decisions with optional structured filters",
        responses={
            200: {
                "description": "Filtered list of decision-bearing edges.",
            },
            503: {"description": "Weave mode is not enabled."},
        },
    )
    async def get_decisions(
        approved_by: Optional[str] = Query(
            default=None,
            description="Filter: only include decisions approved by this entity name.",
            example="VP_Smith",
        ),
        approved_via: Optional[str] = Query(
            default=None,
            description="Filter: channel — 'slack', 'zoom', 'email', 'in_person', 'jira', 'system'.",
            example="slack",
        ),
        policy_ref: Optional[str] = Query(
            default=None,
            description="Filter: only include decisions referencing this policy.",
            example="DiscountPolicy_Standard",
        ),
        min_confidence: float = Query(
            default=0.0,
            ge=0.0,
            le=1.0,
            description="Minimum confidence score threshold.",
        ),
        active_as_of: Optional[str] = Query(
            default=None,
            description="ISO-8601 date (YYYY-MM-DD); only include decisions valid on this date.",
            example="2024-09-01",
        ),
    ):
        """
        Return all knowledge graph edges that carry a `RelationContext` with a
        `decision_trace`, optionally filtered by approval chain fields.

        Filter parameters are ANDed: all specified filters must match.

        **Requires:** `WEAVE_ENABLE_QUADRUPLE=true` in server configuration.
        """
        _require_quadruple(rag)
        try:
            raw = await rag.get_all_decisions(
                approved_by=approved_by,
                approved_via=approved_via,
                policy_ref=policy_ref,
                min_confidence=min_confidence,
                active_as_of=active_as_of,
            )
            decisions = [
                DecisionResult(
                    src_id=item["src_id"],
                    tgt_id=item["tgt_id"],
                    relation_context=_rc_to_pydantic(item["relation_context"]),
                )
                for item in raw
            ]
            return DecisionsListResponse(
                total_count=len(decisions),
                decisions=decisions,
            )
        except HTTPException:
            raise
        except Exception as e:
            logger.error(f"get_decisions error: {e}", exc_info=True)
            raise HTTPException(status_code=500, detail=str(e))

    @router.post(
        "/graph/decisions/reindex",
        dependencies=[Depends(combined_auth)],
        summary="Rebuild the decision search indices from the graph (source of truth)",
        responses={
            200: {"description": "Number of decision edges re-projected."},
            503: {"description": "Weave mode is not enabled."},
        },
    )
    async def reindex_decisions(
        wait: bool = Query(
            default=False,
            description="Run inline and return the count (for scripts). Default: run in "
            "the background and return immediately.",
        ),
    ):
        """Re-project every rc-bearing graph edge into the derived search indices
        (``relationships_vdb`` for normal retrieval + ``decisions_vdb`` for precedent
        search). The graph edge is the single source of truth; this makes the vector
        indices rebuildable and repairs any drift. Idempotent.

        Backend-agnostic and fast where the graph supports a filtered edge lookup. By
        default it runs in the background so the request never blocks; pass
        ``?wait=true`` to run inline and get the reindexed count."""
        _require_quadruple(rag)
        if wait:
            try:
                return await rag.reindex_decisions()
            except Exception as e:
                logger.error(f"reindex_decisions error: {e}", exc_info=True)
                raise HTTPException(status_code=500, detail=str(e))

        import asyncio

        ws = getattr(rag, "workspace", "") or "default"
        if ws in _reindex_running:
            return {"status": "already_running", "workspace": ws}
        _reindex_running.add(ws)

        async def _run():
            try:
                await rag.reindex_decisions()
            except Exception as e:  # pragma: no cover - background best-effort
                logger.error(f"background reindex_decisions error: {e}", exc_info=True)
            finally:
                _reindex_running.discard(ws)

        # Keep a strong reference until the task completes so it isn't GC'd mid-run.
        task = asyncio.create_task(_run())
        _reindex_tasks.add(task)
        task.add_done_callback(_reindex_tasks.discard)
        return {"status": "started", "workspace": ws}

    @router.post(
        "/graph/vectors/reindex",
        dependencies=[Depends(combined_auth)],
        summary="Rebuild entity & relation vector indices from the graph (source of truth)",
        responses={
            200: {"description": "Counts of entities/relationships/decisions reindexed."},
            503: {"description": "Weave mode is not enabled."},
        },
    )
    async def reindex_graph_vectors(
        wait: bool = Query(
            default=False,
            description="Run inline and return counts (for scripts). Default: run in the "
            "background and return immediately.",
        ),
    ):
        """Rebuild ``entities_vdb`` and ``relationships_vdb`` from the graph, using the
        exact record shape ingestion writes — recovers from vector drift (embedding-model
        or storage changes, partial write failures) so search and dedup keep working.
        Decision projections are overlaid afterward. The graph is the source of truth;
        this is idempotent and off the ingest path."""
        _require_quadruple(rag)
        if wait:
            try:
                return await rag.reindex_graph_vectors()
            except Exception as e:
                logger.error(f"reindex_graph_vectors error: {e}", exc_info=True)
                raise HTTPException(status_code=500, detail=str(e))

        import asyncio

        ws = getattr(rag, "workspace", "") or "default"
        key = f"{ws}:vectors"
        if key in _reindex_running:
            return {"status": "already_running", "workspace": ws}
        _reindex_running.add(key)

        async def _run():
            try:
                await rag.reindex_graph_vectors()
            except Exception as e:  # pragma: no cover - background best-effort
                logger.error(f"background reindex_graph_vectors error: {e}", exc_info=True)
            finally:
                _reindex_running.discard(key)

        task = asyncio.create_task(_run())
        _reindex_tasks.add(task)
        task.add_done_callback(_reindex_tasks.discard)
        return {"status": "started", "workspace": ws}

    @router.get(
        "/graph/connectivity",
        dependencies=[Depends(combined_auth)],
        summary="Graph connectivity report (components, isolates, degree)",
        responses={
            200: {"description": "Connectivity metrics for the workspace graph."},
            503: {"description": "Weave mode is not enabled."},
        },
    )
    async def graph_connectivity(
        sample_isolates: int = Query(
            default=20, ge=0, le=200,
            description="How many isolated node names to include as a sample.",
        ),
    ):
        """Measure how connected the knowledge graph is — the baseline metric for the
        graph-quality work (dedup / garbage filtering / connectivity). Returns node &
        edge counts, isolate count and %, connected-component count, largest-component
        share, a degree summary, and a small sample of isolated nodes."""
        _require_quadruple(rag)
        try:
            return await rag.connectivity_report(sample_isolates=sample_isolates)
        except Exception as e:
            logger.error(f"graph_connectivity error: {e}", exc_info=True)
            raise HTTPException(status_code=500, detail=str(e))

    @router.post(
        "/graph/connectivity/rescue",
        dependencies=[Depends(combined_auth)],
        summary="Reconnect isolated nodes with LLM-verified real edges",
    )
    async def connectivity_rescue(
        apply: bool = Query(default=True, description="Add edges (false = preview isolates)."),
        limit: int = Query(default=50, ge=1, le=2000),
        max_candidates: int = Query(default=8, ge=1, le=20),
    ):
        """Layer 3: for each degree-0 node, embedding proposes candidates and the LLM
        adds only relationships the descriptions support (asserted edges only)."""
        _require_quadruple(rag)
        try:
            return await rag.rescue_isolates(
                apply=apply, limit=limit, max_candidates=max_candidates)
        except Exception as e:
            logger.error(f"connectivity_rescue error: {e}", exc_info=True)
            raise HTTPException(status_code=500, detail=str(e))

    @router.post(
        "/graph/prune/isolates",
        dependencies=[Depends(combined_auth)],
        summary="Propose-only pruning of degree-0 isolates (opt-in, quarantine-backed)",
    )
    async def prune_isolates(
        apply: bool = Query(default=False,
                            description="Default false = preview. true moves isolates to the restorable quarantine."),
        limit: int = Query(default=100000, ge=1, le=1000000),
    ):
        """D13: run AFTER connectivity repair. Previews degree-0 isolates by default;
        degree-1 leaves are never touched (real single-relationship entities)."""
        _require_quadruple(rag)
        try:
            return await rag.prune_isolates(apply=apply, limit=limit)
        except Exception as e:
            logger.error(f"prune_isolates error: {e}", exc_info=True)
            raise HTTPException(status_code=500, detail=str(e))

    @router.post(
        "/graph/community/build",
        dependencies=[Depends(combined_auth)],
        summary="Detect communities + summarise them for the thematic global mode",
    )
    async def community_build(
        min_size: int = Query(default=3, ge=2, le=100),
        max_communities: int = Query(default=300, ge=1, le=5000),
    ):
        """Layer 4: Louvain community detection + per-community LLM summaries, indexed
        for the community-summary "global" retrieval mode."""
        _require_quadruple(rag)
        try:
            return await rag.build_communities(
                min_size=min_size, max_communities=max_communities)
        except Exception as e:
            logger.error(f"community_build error: {e}", exc_info=True)
            raise HTTPException(status_code=500, detail=str(e))

    @router.post(
        "/graph/community/query",
        dependencies=[Depends(combined_auth)],
        summary="Thematic 'global' answer over community summaries",
    )
    async def community_query(request: CommunityQueryRequest):
        _require_quadruple(rag)
        try:
            return await rag.community_query(request.query, top_k=request.top_k)
        except Exception as e:
            logger.error(f"community_query error: {e}", exc_info=True)
            raise HTTPException(status_code=500, detail=str(e))

    @router.get(
        "/graph/communities",
        dependencies=[Depends(combined_auth)],
        summary="List detected communities (title, size, members)",
    )
    async def community_list():
        _require_quadruple(rag)
        try:
            return {
                "communities": rag.community_store.list(rag.workspace),
                "summary": rag.community_store.summary(rag.workspace),
            }
        except Exception as e:
            logger.error(f"community_list error: {e}", exc_info=True)
            raise HTTPException(status_code=500, detail=str(e))

    # ── Entity deduplication (Graph-Quality v-next, Topic 1) ──────────────────

    def _require_dedup(rag) -> None:
        _require_quadruple(rag)
        if not getattr(rag, "dedup_enabled", True):
            raise HTTPException(
                status_code=403,
                detail="Deduplication is disabled (WEAVE_DEDUP_ENABLED=false).",
            )

    @router.post(
        "/graph/dedup/scan",
        dependencies=[Depends(combined_auth)],
        summary="Scan existing entities for near-duplicates (conservative, type-aware)",
    )
    async def dedup_scan(
        apply: bool = Query(default=True, description="Apply hard-threshold auto-merges."),
        limit: int = Query(default=5000, ge=1, le=100000),
    ):
        """Layer E: auto-merge near-certain duplicates (reversibly) and queue the
        gray zone for the LLM sweep. Runs off the ingest path."""
        _require_dedup(rag)
        try:
            return await rag.deduplicate_entities(apply=apply, limit=limit)
        except Exception as e:
            logger.error(f"dedup_scan error: {e}", exc_info=True)
            raise HTTPException(status_code=500, detail=str(e))

    @router.post(
        "/graph/dedup/sweep",
        dependencies=[Depends(combined_auth)],
        summary="LLM-adjudicate the gray-zone review queue and apply confirmed merges",
    )
    async def dedup_sweep():
        """Layer C: batched LLM adjudication (+ canonical naming) of the review queue."""
        _require_dedup(rag)
        try:
            return await rag.run_dedup_sweep()
        except Exception as e:
            logger.error(f"dedup_sweep error: {e}", exc_info=True)
            raise HTTPException(status_code=500, detail=str(e))

    @router.get(
        "/graph/dedup/review",
        dependencies=[Depends(combined_auth)],
        summary="Pending gray-zone duplicate pairs awaiting adjudication",
    )
    async def dedup_review():
        _require_quadruple(rag)
        try:
            return {
                "pending": rag.dedup_store.list_pending(rag.workspace),
                "summary": rag.dedup_store.summary(rag.workspace),
            }
        except Exception as e:
            logger.error(f"dedup_review error: {e}", exc_info=True)
            raise HTTPException(status_code=500, detail=str(e))

    @router.get(
        "/graph/entities/merges",
        dependencies=[Depends(combined_auth)],
        summary="Audit log of entity merges (reversible)",
    )
    async def entity_merges(include_undone: bool = Query(default=False)):
        _require_quadruple(rag)
        try:
            recs = rag.dedup_store.list_merges(rag.workspace, include_undone=include_undone)
            return {"merges": [m.to_dict() for m in recs]}
        except Exception as e:
            logger.error(f"entity_merges error: {e}", exc_info=True)
            raise HTTPException(status_code=500, detail=str(e))

    @router.post(
        "/graph/entities/unmerge",
        dependencies=[Depends(combined_auth)],
        summary="Reverse a recorded entity merge by id",
    )
    async def entity_unmerge(merge_id: str = Query(..., min_length=1)):
        _require_quadruple(rag)
        try:
            ok = await rag.unmerge_entity(merge_id)
            if not ok:
                raise HTTPException(status_code=404,
                                    detail=f"No live merge '{merge_id}'.")
            return {"status": "ok", "merge_id": merge_id}
        except HTTPException:
            raise
        except Exception as e:
            logger.error(f"entity_unmerge error: {e}", exc_info=True)
            raise HTTPException(status_code=500, detail=str(e))

    # ── Garbage filtering — quarantine review (Graph-Quality v-next, Topic 2) ──

    @router.post(
        "/graph/garbage/scan",
        dependencies=[Depends(combined_auth)],
        summary="Retroactively remove garbage nodes from an existing graph",
    )
    async def garbage_scan(
        apply: bool = Query(default=True, description="Remove rejects (false = preview)."),
        limit: int = Query(default=100000, ge=1, le=1000000),
    ):
        """Run the node-quality filter over every existing entity; quarantine and
        remove the rejects (restorable). ``apply=false`` previews without changing."""
        _require_quadruple(rag)
        try:
            return await rag.scan_garbage(apply=apply, limit=limit)
        except Exception as e:
            logger.error(f"garbage_scan error: {e}", exc_info=True)
            raise HTTPException(status_code=500, detail=str(e))

    @router.get(
        "/graph/quarantine",
        dependencies=[Depends(combined_auth)],
        summary="Nodes rejected by the quality filter (restorable)",
    )
    async def quarantine_list():
        _require_quadruple(rag)
        try:
            return {
                "items": rag.quarantine_store.list(rag.workspace),
                "summary": rag.quarantine_store.summary(rag.workspace),
            }
        except Exception as e:
            logger.error(f"quarantine_list error: {e}", exc_info=True)
            raise HTTPException(status_code=500, detail=str(e))

    @router.post(
        "/graph/quarantine/restore",
        dependencies=[Depends(combined_auth)],
        summary="Restore a quarantined node into the graph",
    )
    async def quarantine_restore(name: str = Query(..., min_length=1)):
        _require_quadruple(rag)
        try:
            item = rag.quarantine_store.pop(rag.workspace, name)
            if item is None:
                raise HTTPException(status_code=404, detail=f"No quarantined node '{name}'.")
            await rag.acreate_entity(name, {
                "entity_type": item.get("entity_type") or "UNKNOWN",
                "description": item.get("description") or name,
            })
            return {"status": "restored", "name": name}
        except HTTPException:
            raise
        except Exception as e:
            logger.error(f"quarantine_restore error: {e}", exc_info=True)
            raise HTTPException(status_code=500, detail=str(e))

    @router.post(
        "/graph/quarantine/discard",
        dependencies=[Depends(combined_auth)],
        summary="Permanently drop a quarantined node",
    )
    async def quarantine_discard(name: str = Query(..., min_length=1)):
        _require_quadruple(rag)
        try:
            ok = rag.quarantine_store.pop(rag.workspace, name) is not None
            if not ok:
                raise HTTPException(status_code=404, detail=f"No quarantined node '{name}'.")
            return {"status": "discarded", "name": name}
        except HTTPException:
            raise
        except Exception as e:
            logger.error(f"quarantine_discard error: {e}", exc_info=True)
            raise HTTPException(status_code=500, detail=str(e))

    return router
